{
  description = "Nix packages for the Project Colony ecosystem";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      # Versions and hashes are generated by scripts/update.sh. No package body
      # ever contains a hand-edited hash, so a release bump is a one-line diff.
      sources = nixpkgs.lib.importJSON ./sources.json;

      packagesFor = pkgs: {
        spherecord = pkgs.callPackage ./pkgs/spherecord/package.nix { inherit sources; };
      };
    in
    {
      overlays.default = final: _prev: packagesFor final;

      packages = forAllSystems (
        system:
        let
          ps = packagesFor nixpkgs.legacyPackages.${system};
        in
        ps // { default = ps.spherecord; }
      );
    };
}
